package sala.xevi.awale

const val PLAYER2_LEVEL: String = "player2level"
const val BACKGROUND_BOARD: String = "backgBoard"
const val DEFAULT_BACK_BOARD: String = "#AF7319"
const val TIME_GAME: String = "timeGame"
const val GAME: String = "game"
const val IS_TIME_ACTIVE = "isTimeActive"
const val CUSTOM_BOARD_ACTIVE = "isCustomBActive"
const val RED_SLIDER = "redSlider"
const val GREEN_SLIDER = "greenSlider"
const val BLUE_SLIDER = "blueSlider"
const val MINUTES = "minutes"
const val SAVED_GAME = "saved_game"
const val SPEED_ANIMATION = "speedAnimation"
const val PLAYER1_NAME: String = "player1Name"
const val PLAYER2_NAME: String = "player2Name"
const val SHOWTIP: String = "showTip"